
package Interfaz;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Jose
 */
@SuppressWarnings("serial")
public class grafico extends javax.swing.JFrame {

  /**
   * Creates new form grafico
   */
  public grafico() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextField1 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTextField1.setText("Respuestas malas");

    jTextField3.setText("Preguntas sin responder");
    jTextField3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField3ActionPerformed(evt);
      }
    });

    jTextField4.setText("respuestas buenas");

    jButton1.setText("Generar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 593,
            Short.MAX_VALUE));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 231,
            Short.MAX_VALUE));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(286, 286, 286)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup().addGap(96, 96, 96).addComponent(jPanel1,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(89, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextField3ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    int n1 = Integer.parseInt(jTextField1.getText());
    int n2 = Integer.parseInt(jTextField3.getText());
    int n3 = Integer.parseInt(jTextField4.getText());

    DefaultPieDataset datos = new DefaultPieDataset();
    datos.setValue("Respuestas buenas", n1);
    datos.setValue("Respuestas malas", n2);
    datos.setValue("Sin contestar", n3);

    JFreeChart grafico_circular =
        ChartFactory.createPieChart("Respuestas", datos, true, true, false);
    ChartPanel panel = new ChartPanel(grafico_circular);
    // panel.setMouseWheelEnabled(true);
    panel.setPreferredSize(new Dimension(593, 231));

    jPanel1.setLayout(new BorderLayout());
    jPanel1.add(panel, BorderLayout.NORTH);
    pack();
    repaint();
  }// GEN-LAST:event_jButton1ActionPerformed


  public void generarGrafico(int pBuenas, int pMalas, int pSinContestar) {
    int buenas = pBuenas;
    int malas = pMalas;
    int sinContestar = pSinContestar;

    DefaultPieDataset datos = new DefaultPieDataset();
    datos.setValue("Respuestas buenas", buenas);
    datos.setValue("Respuestas malas", malas);
    datos.setValue("Sin contestar", sinContestar);

    JFreeChart graficoCircular =
        ChartFactory.createPieChart("Respuestas", datos, true, true, false);
    ChartPanel panelGrafico = new ChartPanel(graficoCircular);
    panelGrafico.setPreferredSize(new Dimension(593, 231));

    JOptionPane.showMessageDialog(this, panelGrafico, "Gráfico Circular",
        JOptionPane.PLAIN_MESSAGE);
  }

  /**
   * @param args the command line arguments
   */


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables
}
