package vista;

import controlador.VistaPrincipalController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DateFormatter;
import modelo.Curso;
import modelo.Escuela;
import modelo.Plan;

/**
 *
 * Interfaz grafica para Crear Plan.
 * @author gvargasr
 */
public class CrearPlan extends javax.swing.JFrame {

  /**
   * Creates new form CrearPlan
   */
  public CrearPlan() {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jButton8 = new javax.swing.JButton();
    jLabel15 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel16 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jComboBox3 = new javax.swing.JComboBox<>();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jButton9 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    fechaTextField = new javax.swing.JFormattedTextField(
        new DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy")));
    jButton10 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel3.setPreferredSize(new java.awt.Dimension(450, 450));

    jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel13.setText("Registro de Planes de Estudio");

    jLabel14.setText("Código del plan de estudios: ");

    jButton8.setText("Agregar plan");
    jButton8.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel15.setText("Escuela propietaria del plan:");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jLabel16.setText("Vigencia del plan de estudios: ");

    jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jComboBox2
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"0", "1", "2", "3", "4"}));
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox2ActionPerformed(evt);
      }
    });

    jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Bloque 1", "Bloque 2",
        "Bloque 3", "Bloque 4", "Bloque 5", "Bloque 6", "Bloque 7", "Bloque 8"}));
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox3ActionPerformed(evt);
      }
    });

    jLabel17.setText("Código del curso:");

    jLabel18.setText("Bloque");

    jButton9.setText("Cerrar");
    jButton9.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    fechaTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fechaTextFieldActionPerformed(evt);
      }
    });

    jButton10.setText("Limpiar");
    jButton10.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout
        .setHorizontalGroup(jPanel3Layout
            .createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup().addGap(20, 20, 20)
                .addGroup(jPanel3Layout
                    .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 215,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout
                        .createSequentialGroup()
                        .addGroup(jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup().addGap(10, 10, 10)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                .createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                    .addComponent(fechaTextField,
                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jComboBox3,
                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1,
                                        javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel3Layout.createSequentialGroup().addGap(45, 45, 45)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173,
                    Short.MAX_VALUE)
                .addComponent(jLabel18).addGap(88, 88, 88))
            .addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup().addGap(133, 133, 133).addComponent(
                    jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup().addGap(51, 51, 51).addComponent(
                    jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup().addGap(59, 59, 59).addComponent(
                    jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 308,
                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel3Layout.setVerticalGroup(jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup().addGap(14, 14, 14)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createSequentialGroup().addGap(4, 4, 4).addComponent(
                    jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30,
                    Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(fechaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30,
                    Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17).addComponent(jLabel18))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18).addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(27, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addComponent(jPanel3,
            javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jComboBox2ActionPerformed

  private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox3ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jComboBox3ActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextField1ActionPerformed

  private void fechaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fechaTextFieldActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_fechaTextFieldActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    VistaPrincipalController.mostrar();
    this.dispose();
  }// GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    controlador.CrearPlanController.eventoBotonLimpiar();
  }// GEN-LAST:event_jButton4ActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    String escuelaActual = (String) jComboBox1.getSelectedItem();
    ArrayList<Escuela> listaEscuelas = VistaPrincipalController.modelo.getEscuelas();
    for (Escuela escuela : listaEscuelas) {
      if (escuela.getNombre().equals(escuelaActual)) {
        updateCursos(escuela.getCursos());
        break;
      }
    }
  }// GEN-LAST:event_jComboBox1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    // Get he text from the text fields
    String numberString = jTextField1.getText();
    String dateString = fechaTextField.getText();
    String codigo = (String) jComboBox2.getSelectedItem();

    // Validar jTextField1 para asegurarse que es un entero entre 1000 y 9999
    try {
      int number = Integer.parseInt(numberString);
      if (number < 1000 || number > 9999) {
        JOptionPane.showMessageDialog(this, "El código de plan debe estar entre 1000 y 9999",
            "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
      }
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Por favor, ingrese un código válido",
          "Error de Validación", JOptionPane.ERROR_MESSAGE);
      return;
    }
    // Validar fechaTextField para asegurar el formato dd/MM/yyyy
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    try {
      LocalDate date = LocalDate.parse(dateString, formatter);
    } catch (DateTimeParseException e) {
      JOptionPane.showMessageDialog(this, "La fecha de vigencia debe tener el formato dd/MM/yyyy",
          "Error de Validación", JOptionPane.ERROR_MESSAGE);
      return;
    }
    Escuela escuela = VistaPrincipalController.modelo.buscarEscuela((String)jComboBox1.getSelectedItem());
    
    Plan planActual = null;
    for (Plan plan : escuela.getPlanDeEstudio()) {
      if (plan.getCodigo() == Integer.parseInt(numberString)) {
        planActual = plan;
        break;
      }
    }
    
    if (planActual == null) {
      JOptionPane.showMessageDialog(this, "Curso agregado al plan exitosamente!",
          "Agregar curso", JOptionPane.INFORMATION_MESSAGE);
      controlador.CrearPlanController.eventoBotonRegistrarCurso();
    } else if (planActual.verificarCursoCodigo(codigo)) {
      JOptionPane.showMessageDialog(this, "Curso ya esta incluido en el plan",
          "Agregar curso", JOptionPane.ERROR_MESSAGE);
    } else {
      controlador.CrearPlanController.eventoBotonRegistrarCurso();
      JOptionPane.showMessageDialog(this, "Curso agregado al plan exitosamente!",
          "Agregar curso", JOptionPane.INFORMATION_MESSAGE);
    }

  }// GEN-LAST:event_jButton2ActionPerformed

 /**
  * Main para la interfaz grafica.
  * @param args[] Valor por defecto
  */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CrearPlan.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CrearPlan.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CrearPlan.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CrearPlan.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CrearPlan().setVisible(true);
      }
    });
  }

 /**
  * Metodo para actualizar la lista de escuelas del jComboBox1 y 2.
  * 
  */
  public void updateEscuelas() {
    ArrayList<Escuela> listaEscuelas = VistaPrincipalController.modelo.getEscuelas();
    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();
    for (Escuela escuela : listaEscuelas) {
      jComboBox1.addItem(escuela.getNombre());
    }
  }

 /**
  * Metodo para actualizar la lista de cursos del jComboBox1.
  * @param listaCursos Lista de cursos.
  */
  public void updateCursos(ArrayList<Curso> listaCursos) {
    jComboBox2.removeAllItems();
    for (Curso curso : listaCursos) {
      if (!curso.getCodigo().equals(jComboBox1.getSelectedItem())) {
        jComboBox2.addItem(curso.getCodigo());
      }
    }
  }

  /**
  * Metodo para limpiar los espacios de la interfaz grafica.
  * 
  */
  public void limpiarEspacios() {
    if (jComboBox1.getItemCount() > 0) {
      jComboBox1.setSelectedIndex(0);
    } else {
    }

    jTextField1.setText("");
    fechaTextField.setText(" ");

    if (jComboBox2.getItemCount() > 0) {
      jComboBox2.setSelectedIndex(0);
    } else {
    }

    if (jComboBox3.getItemCount() > 0) {
      jComboBox3.setSelectedIndex(0);
    } else {
    }
    jTextField1.setText("");
    fechaTextField.setText(" ");

  }

  /**
  * Metodo para obtener el string en jComboBox1.
  * @return jComboBox1
  */
  public JComboBox<String> getjComboBox1() {
    return jComboBox1;
  }

  /**
  * Metodo para obtener el string en jTextField1.
  * @param jComboBox1 Valor por defecto
  */
  public void setjComboBox1(JComboBox<String> jComboBox1) {
    this.jComboBox1 = jComboBox1;
  }

  /**
  * Metodo para obtener el string en jComboBox2.
  * @return  jComboBox2
  */
  public JComboBox<String> getjComboBox2() {
    return jComboBox2;
  }

  /**
  * Metodo para configurar el string en jComboBox2.
  * @param jComboBox2 Valor actual del ComboBox
  */
  public void setjComboBox2(JComboBox<String> jComboBox2) {
    this.jComboBox2 = jComboBox2;
  }

  /**
  * Metodo para obtener el string en jComboBox3.
  * @return  jComboBox3
  */
  public JComboBox<String> getjComboBox3() {
    return jComboBox3;
  }

  /**
  * Metodo para Setear  el string en jComboBox3.
  * @param  jComboBox3 Valor actual del jComboBox
  */
  public void setjComboBox3(JComboBox<String> jComboBox3) {
    this.jComboBox3 = jComboBox3;
  }

  /**
  * Metodo para obtener el string en fechaTextField.
  * @return fechaTextField
  */
  public JTextField getFechaTextField() {
    return fechaTextField;
  }

  /**
  * Metodo para configurar el string en fechaTextField.
  * @param fechaTextField String para actualizar
  */
  public void setFechaTextField(JTextField fechaTextField) {
    this.fechaTextField = fechaTextField;
  }

  /**
  * Metodo para obtener el string en jTextField1.
  * @return jTextField1
  */
  public JTextField getjTextField1() {
    return jTextField1;
  }

  /**
  * Metodo para configurar el string en jTextField1.
  * @param jTextField1 Valor por defecto.
  */
  public void setjTextField1(JTextField jTextField1) {
    this.jTextField1 = jTextField1;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField fechaTextField;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables



}
