package vista;


import controlador.VistaPrincipalController;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Curso;
import modelo.Escuela;

/**
 *
 * Interfaz grafica para Registrar Requisitos y correquisitos.
 * @author gvargasr
 */
public class RegistrarRequisito extends javax.swing.JFrame {

  /**
   * Creates new form RegistrarRequisitos
   */
  public RegistrarRequisito() {
    initComponents();
    setLocationRelativeTo(null);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jComboBox3 = new javax.swing.JComboBox<>();
    jComboBox4 = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Asignar requisitos y correquisitos a un curso");

    jLabel2.setText("Código del curso: ");

    jButton1.setText("Registrar requisito");
    jButton1.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Registrar correquisito");
    jButton2.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel4.setText("Escuela propietaria del curso:");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jLabel6.setText("Requisitos del curso");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jLabel7.setText("Correquisitos del curso");

    jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jComboBox2
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"0", "1", "2", "3", "4"}));
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox2ActionPerformed(evt);
      }
    });

    jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jComboBox3
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1", "2", "3", "4", "5"}));
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox3ActionPerformed(evt);
      }
    });

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));
    jComboBox4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox4ActionPerformed(evt);
      }
    });

    jLabel3.setText("Código del curso:");

    jLabel5.setText("Código del curso:");

    jButton3.setText("Cerrar");
    jButton3.setBorder(
        javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup().addGap(39, 39, 39).addComponent(jLabel1,
                javax.swing.GroupLayout.PREFERRED_SIZE, 384,
                javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup().addGap(140, 140, 140).addComponent(
                jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20)
                .addGroup(jPanel1Layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup().addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                            .createSequentialGroup().addGap(15, 15, 15)
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                    false)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 156,
                                    Short.MAX_VALUE))
                            .addGap(11, 11, 11))
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                        .addGap(18, 18, 18).addComponent(jComboBox1,
                            javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                            javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jComboBox4,
                    javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                    javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(16, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup().addGap(14, 14, 14)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup().addGap(4, 4, 4).addComponent(
                        jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5).addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                    17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18).addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(22, 22, 22)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 15, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    jPanel1.getAccessibleContext().setAccessibleName("");
    jPanel1.getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    String codigo = (String) jComboBox2.getSelectedItem();
    if (codigo != null && !codigo.isEmpty()) {
      if (verificarCodigo(codigo)) {
        if (jComboBox4.getSelectedItem() != null
            && !jComboBox4.getSelectedItem().toString().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Registro exitoso", "Éxito",
              JOptionPane.INFORMATION_MESSAGE);
          // Lógica adicional para registrar Requisito
          controlador.RegistrarRequisitoController.eventoBotonRegistrarRequisito();
        } else {
          JOptionPane.showMessageDialog(this, "Seleccione código válido", "Error",
              JOptionPane.ERROR_MESSAGE);
        }
      } else {
        JOptionPane.showMessageDialog(this, "Codigo ya existente", "Error",
            JOptionPane.ERROR_MESSAGE);
      }
    } else {
      JOptionPane.showMessageDialog(this, "Seleccione código válido", "Error",
          JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_jButton1ActionPerformed


  private boolean verificarCodigo(String codigo) {
    Escuela escuelaActual =
        VistaPrincipalController.modelo.buscarEscuela((String) jComboBox1.getSelectedItem());
    Curso cursoActual = escuelaActual.buscarCurso((String) jComboBox4.getSelectedItem());
    ArrayList<Curso> listaRequisitos = cursoActual.getRequisitos();
    ArrayList<Curso> listaCorrequisitos = cursoActual.getCorrequisitos();
    for (Curso curso : listaRequisitos) {
      if (curso.getCodigo().equals(codigo)) {
        return false;
      }
    }
    for (Curso curso : listaCorrequisitos) {
      if (curso.getCodigo().equals(codigo)) {
        return false;
      }
    }
    return true;
  }

  private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox4ActionPerformed
    // TODO add your handling code here:
    String escuelaActual = (String) jComboBox1.getSelectedItem();
    ArrayList<Escuela> listaEscuelas = VistaPrincipalController.modelo.getEscuelas();
    for (Escuela escuela : listaEscuelas) {
      if (escuela.getNombre().equals(escuelaActual)) {
        updateRequisitos(escuela.getCursos());
        break;
      }
    }
  }// GEN-LAST:event_jComboBox4ActionPerformed

  private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox3ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jComboBox3ActionPerformed

  private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jComboBox2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here
    VistaPrincipalController.mostrar();
    this.dispose();
  }// GEN-LAST:event_jButton3ActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    String escuelaActual = (String) jComboBox1.getSelectedItem();
    ArrayList<Escuela> listaEscuelas = VistaPrincipalController.modelo.getEscuelas();
    for (Escuela escuela : listaEscuelas) {
      if (escuela.getNombre().equals(escuelaActual)) {
        updateCursos(escuela.getCursos());
        updateRequisitos(escuela.getCursos());
        break;
      }
    }
  }// GEN-LAST:event_jComboBox1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    String codigo = (String) jComboBox2.getSelectedItem();
    if (codigo != null && !codigo.isEmpty()) {
      if (verificarCodigo(codigo)) {
        if (jComboBox4.getSelectedItem() != null
            && !jComboBox4.getSelectedItem().toString().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Registro exitoso", "Éxito",
              JOptionPane.INFORMATION_MESSAGE);
          // Lógica adicional para registrar Requisito
          controlador.RegistrarRequisitoController.eventoBotonRegistrarCorrequisito();
        } else {
          JOptionPane.showMessageDialog(this, "Seleccione código válido", "Error",
              JOptionPane.ERROR_MESSAGE);
        }
      } else {
        JOptionPane.showMessageDialog(this, "Codigo ya existente", "Error",
            JOptionPane.ERROR_MESSAGE);
      }
    } else {
      JOptionPane.showMessageDialog(this, "Seleccione código válido", "Error",
          JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_jButton1ActionPerformed



  public void updateCursos(ArrayList<Curso> listaCursos) {
    jComboBox4.removeAllItems();
    for (Curso curso : listaCursos) {
      jComboBox4.addItem(curso.getCodigo());
    }
  }

  public void updateRequisitos(ArrayList<Curso> listaCursos) {
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();
    for (Curso curso : listaCursos) {
      if (!curso.getCodigo().equals(jComboBox4.getSelectedItem())) {
        jComboBox2.addItem(curso.getCodigo());
        jComboBox3.addItem(curso.getCodigo());
      }
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RegistrarRequisito.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RegistrarRequisito.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RegistrarRequisito.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RegistrarRequisito.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RegistrarRequisito().setVisible(true);
      }
    });
  }


  public void updateEscuelas() {
    ArrayList<Escuela> listaEscuelas = VistaPrincipalController.modelo.getEscuelas();
    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();
    jComboBox4.removeAllItems();
    for (Escuela escuela : listaEscuelas) {
      jComboBox1.addItem(escuela.getNombre());
    }
  }

  public JComboBox<String> getjComboBox1() {
    return jComboBox1;
  }

  public JComboBox<String> getjComboBox2() {
    return jComboBox2;
  }

  public JComboBox<String> getjComboBox3() {
    return jComboBox3;
  }

  public JComboBox<String> getjComboBox4() {
    return jComboBox4;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JComboBox<String> jComboBox4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables



}
